version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      # Android the primary container
      - image: library/ubuntu
      - image: circleci/openjdk:8-jdk-node
      #- image: budtmo/docker-android-x86-5.0.1
      #- image: appium/appium:local
      #- image: circleci/ruby:2.7-rc
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/android:api-24
      
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      ANDROID_HOME: /usr/local/android-sdk-linux

    steps:
      - checkout

       # Download and cache dependencies

      # Download dependencies
      - run: cd /opt/repo/; ls
   
