version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers-legacy
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
    - checkout
    - setup_remote_docker: 
         docker_layer_caching: true
    - run: sudo apt update
    - run: chmod +777 chromedriver
    - run: chmod +777 src/chromedriver
    - run: chmod +777 test-output
    - run: java -cp "/home/circleci/repo/lib/*:/home/circleci/repo/bin/" org.testng.TestNG testng.xml
    
    - store_artifacts:
          path:  test-output
