version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      # Android the primary container
      - image: reactnativecommunity/react-native-android:2019-5-29
      
    environment:
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      - run: 
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-17;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-17;default;armeabi-v7a" && echo "no"
      #- run: cd /opt/android/sdk/emulator/ ; ls
      
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && ${ANDROID_HOME}/emulator/emulator -avd test -no-audio -no-window
          background: true
      
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
          #background: true
      
      - run:
          name: Run TestNG Tests
          command: java -cp "lib/*:bin/" org.testng.TestNG testng.xml
          
      - store_artifacts:
          path:  test-output
