# CircleCi configuration version
version: 2

jobs:
  build:
    docker:
      # specific environment version to avoid incompatible updates
      #- image: bitriseio/docker-android:v2017_09_09-06_45-b744
    #docker:
      - image: circleci/node:4.8.2

    working_directory: ~/workspace

    steps:
    - run: 
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb
    - run: 
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb

      #- run:
      #    name: Install custom system image
      #    command: sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
      #    environment:
      #      TERM: dumb

      - run:
          name: Create avd
       #   command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb

      - checkout
      - run: 
        name: Install node 
        command: |
             curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
             sudo apt-get install -y nodejs
             sudo apt-get install -y build-essential
             sudo apt-get install build-essential curl git m4 python-setuptools ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
      
      - run: 
          name: Install appium server
          command: |
                    sudo npm update -g
                    sudo npm install appium
                    sudo npm install wd
       
      - run: 
          name: Start appium server
          command: appium &
          background: true
