# CircleCi configuration version
version: 2

jobs:
  build:
    docker:
      # specific environment version to avoid incompatible updates
      - image: circleci/android:api-29-ndk
      #- image: reactnativecommunity/react-native-android:2019-5-29
    #docker:
      #- image: circleci/node:9.9.0
      #- image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
    - run: cd /lib/x86_64-linux-gnu/; ls; sudo ln -sf libudev.so.1 libudev.so.0; ls
    - run: 
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb
    - run: 
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb
    - run: java -version
    - run: yes | sdkmanager --licenses || exit 0
    - run: yes | sdkmanager --update || exit 0
    
    #- run: sudo apt-get install pulseaudio
    
      #- run:
      #    name: Install custom system image
      #    command: sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
      #    environment:
      #      TERM: dumb
    - run:
          name: Create avd
       #   command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a" && echo "no"
          environment:
            TERM: dumb
    - run: cd /lib/ ; ls
    - run:
          name: Start emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && ${ANDROID_HOME}/emulator/emulator -avd test -no-audio -no-boot-anim -no-window -verbose
          background: true
          environment:
            TERM: dumb

    - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            adb wait-for-device
            # unlock the emulator screen
            sleep 320
            adb shell input keyevent 82
          #background: true
          no_output_timeout: 15m
    - run: nodejs --version
    - run: 
          name: Install appium server
          command: |
                    sudo update -g
                    sudo install appium
                    sudo install wd
       
    - run: 
          name: Start appium server
          command: appium
          background: true
    - run: chmod +777 /root/workspace/bin
    #- run: java -cp "/root/workspace/lib*:/root/workspace/bin/" org.testng.TestNG testng.xml
    - run: java -cp "/root/workspace/lib/eclipse.jar:/root/workspace/lib/beanshell.bsh.b6.jar:/root/workspace/lib/snakeyaml.jar:/root/workspace/lib/selenium-server-standalone-3.141.59.jar:/root/workspace/lib/testng-6.14.3.jar:/root/workspace/lib/jcommander-1.7.jar:/root/workspace/bin/" org.testng.TestNG testng.xml
    
    - store_artifacts:
          path:  test-output
