version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      # Android the primary container
      #- image: reactnativecommunity/react-native-android:latest
      - image: circleci/openjdk:8-jdk
      #- image: circleci/ruby:2.7-rc
      
    environment:
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504
      #- run: apt-get install -y sudo
      #- run: ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
      #- run: export PATH=”$HOME/.linuxbrew/bin:$PATH”; export MANPATH=”$HOME/.linuxbrew/share/man:$MANPATH”; export INFOPATH=”$HOME/.linuxbrew/share/info:$INFOPATH”
      #- run: sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
      #- run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
      
      #- run: google-chrome --version
      - run:
          name: Run TestNG Tests
          command: java -cp "lib/*:bin/" org.testng.TestNG testng.xml
          
      - store_artifacts:
          path:  test-output
