version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      # Android the primary container
      - image: library/ubuntu
      #- image: circleci/android:api-24-alpha
      #- image: circleci/openjdk:8-jdk
      #- image: circleci/ruby:2.7-rc
      
    environment:
      JVM_OPTS: -Xmx3200m
      
    steps:
      - checkout
      - run: sudo add-apt-repository ppa:webupd8team/java; sudo apt-get update; sudo apt-get install oracle-java8-installer
      - run: sudo apt-get install oracle-java8-set-default
      - run: sudo unzip android-studio-ide-141.2178183-linux.zip -d /opt
      - run: ./studio.sh
      
      - run: 
          name: List available targets and other sdk modules
          command: sudo sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a" && echo "no"
      #- run: cd /opt/android/sdk/emulator/ ; ls
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && ${ANDROID_HOME}/emulator/emulator -avd test -no-boot-anim -no-window -no-accel
          background: true
      
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            adb wait-for-device
            # unlock the emulator screen
            sleep 320
            adb shell input keyevent 82
          #background: true
          no_output_timeout: 15m
      #- run: abd 
      - run:
          name: Install appium server
          command: |
             npm update
             npm install appium@1.11.0
             npm install wd
             npm install appium-doctor
      #- run: appium-doctor       
      - run:
          name: Start appium server
          command: appium -a 127.0.0.1 -p 4723 &
          #background: true
          no_output_timeout: 1m
      #- run: google-chrome --version
      - run:
          name: Run TestNG Tests
          command: java -cp "lib/*:bin/" org.testng.TestNG testng.xml
          
      - store_artifacts:
          path:  test-output
